### ISSUE TITLE
Wallet not synchonizing.

### ISSUE THREAD

**Issue by ajayspi** [hivewallet/discussions#30] opened 2015-03-10 15:07 UTC
My wallet is not opening please check.

![hive](https://cloud.githubusercontent.com/assets/4329089/6577593/356a2eba-c765-11e4-975a-07438217dc62.PNG)

**Comment by ghost** [comment] 2015-03-11 06:12
Do you have any extensions etc installed on your machine that are playing with localization settings or something like this?

**Comment by ajayspi** [comment] 2015-03-11 12:28
i tried in my ipad my mobile and on web nothing works

**Comment by ajayspi** [comment] 2015-03-11 12:28
i have no idea on extensions
this is the issue
https://github.com/hivewallet/hive-js/issues/233

**Comment by ghost** [comment] 2015-03-11 19:45
I don't think this is exactly the same issue, @weilu do you agree ? What extensions do you have installed in your browser? And which browser are you using on each platform?

**Comment by weilu** [comment] 2015-03-14 03:17
duplicate of #233

**Closed as completed by weilu** 2015-03-14 03:17 UTC
